// langs.js – VScanPro langues UI (FR, EN, DE, IT, ES, PT, PT-BR)

window.VSCAN_LANGS = {
  fr: {
    scan_document: "Scanner un document",
    import_gallery: "Importer depuis la galerie",
    history: "Historique",
    add_signature: "Ajouter une signature",
    add_watermark: "Ajouter un filigrane",
    mask_tool: "Masquer / flouter",
    options: "Options du document",
    export_pdf: "Exporter en PDF",
    close: "Fermer",
    document_options: "Options du document",
    choose_signature: "Signature avancée :",
    edit_signature: "Modifier la signature",
    signature_hint: "Glissez pour déplacer, pincez pour redimensionner",
    watermark: "Filigrane :",
    pdf_password: "Protéger le PDF (mot de passe) :",
    premium_only: "(Premium)",
    document_type: "Type de document détecté :",
    cachet: "Ajouter cachet automatique :",
    center: "Centré",
    diagonal: "Diagonale",
    bottom: "Bas",
    open: "Ouvrir",
    premium: "Passer Premium",
    premium_hint: "Débloquez toutes les options pros et supprimez les pubs",
    dark_mode: "Mode Sombre",
    light_mode: "Mode Clair",
    confirm: "Confirmer",
    history_empty: "Aucun document enregistré.",
    doc_facture: "Facture",
    doc_pieceid: "Pièce d'identité",
    doc_note: "Note manuscrite",
    doc_autre: "Autre document",
    delete: "Supprimer",
    rename: "Renommer",
    important: "Marquer comme important"
  },
  en: {
    scan_document: "Scan a document",
    import_gallery: "Import from gallery",
    history: "History",
    add_signature: "Add signature",
    add_watermark: "Add watermark",
    mask_tool: "Mask / blur",
    options: "Document options",
    export_pdf: "Export as PDF",
    close: "Close",
    document_options: "Document options",
    choose_signature: "Advanced signature:",
    edit_signature: "Edit signature",
    signature_hint: "Drag to move, pinch to resize",
    watermark: "Watermark:",
    pdf_password: "Protect PDF (password):",
    premium_only: "(Premium)",
    document_type: "Detected document type:",
    cachet: "Add automatic seal:",
    center: "Center",
    diagonal: "Diagonal",
    bottom: "Bottom",
    open: "Open",
    premium: "Go Premium",
    premium_hint: "Unlock all pro options and remove ads",
    dark_mode: "Dark Mode",
    light_mode: "Light Mode",
    confirm: "Confirm",
    history_empty: "No documents saved.",
    doc_facture: "Invoice",
    doc_pieceid: "ID document",
    doc_note: "Handwritten note",
    doc_autre: "Other document",
    delete: "Delete",
    rename: "Rename",
    important: "Mark as important"
  },
  de: {
    scan_document: "Dokument scannen",
    import_gallery: "Aus Galerie importieren",
    history: "Verlauf",
    add_signature: "Unterschrift hinzufügen",
    add_watermark: "Wasserzeichen hinzufügen",
    mask_tool: "Bereich maskieren / verwischen",
    options: "Dokumentoptionen",
    export_pdf: "Als PDF exportieren",
    close: "Schließen",
    document_options: "Dokumentoptionen",
    choose_signature: "Erweiterte Unterschrift:",
    edit_signature: "Unterschrift bearbeiten",
    signature_hint: "Zum Verschieben ziehen, zum Skalieren zusammendrücken",
    watermark: "Wasserzeichen:",
    pdf_password: "PDF schützen (Passwort):",
    premium_only: "(Premium)",
    document_type: "Erkannter Dokumenttyp:",
    cachet: "Automatischen Stempel hinzufügen:",
    center: "Zentriert",
    diagonal: "Diagonal",
    bottom: "Unten",
    open: "Öffnen",
    premium: "Premium aktivieren",
    premium_hint: "Alle Pro-Optionen freischalten und Werbung entfernen",
    dark_mode: "Dunkler Modus",
    light_mode: "Heller Modus",
    confirm: "Bestätigen",
    history_empty: "Keine gespeicherten Dokumente.",
    doc_facture: "Rechnung",
    doc_pieceid: "Ausweisdokument",
    doc_note: "Handschriftliche Notiz",
    doc_autre: "Anderes Dokument",
    delete: "Löschen",
    rename: "Umbenennen",
    important: "Als wichtig markieren"
  },
  it: {
    scan_document: "Scansiona un documento",
    import_gallery: "Importa dalla galleria",
    history: "Cronologia",
    add_signature: "Aggiungi firma",
    add_watermark: "Aggiungi filigrana",
    mask_tool: "Nascondi / sfoca",
    options: "Opzioni documento",
    export_pdf: "Esporta come PDF",
    close: "Chiudi",
    document_options: "Opzioni documento",
    choose_signature: "Firma avanzata:",
    edit_signature: "Modifica firma",
    signature_hint: "Trascina per spostare, pizzica per ridimensionare",
    watermark: "Filigrana:",
    pdf_password: "Proteggi PDF (password):",
    premium_only: "(Premium)",
    document_type: "Tipo di documento rilevato:",
    cachet: "Aggiungi sigillo automatico:",
    center: "Centrato",
    diagonal: "Diagonale",
    bottom: "In basso",
    open: "Apri",
    premium: "Attiva Premium",
    premium_hint: "Sblocca tutte le opzioni pro e rimuovi gli annunci",
    dark_mode: "Modalità scura",
    light_mode: "Modalità chiara",
    confirm: "Conferma",
    history_empty: "Nessun documento salvato.",
    doc_facture: "Fattura",
    doc_pieceid: "Documento d'identità",
    doc_note: "Nota scritta a mano",
    doc_autre: "Altro documento",
    delete: "Elimina",
    rename: "Rinomina",
    important: "Segna come importante"
  },
  es: {
    scan_document: "Escanear documento",
    import_gallery: "Importar desde galería",
    history: "Historial",
    add_signature: "Añadir firma",
    add_watermark: "Añadir marca de agua",
    mask_tool: "Enmascarar / desenfocar",
    options: "Opciones del documento",
    export_pdf: "Exportar como PDF",
    close: "Cerrar",
    document_options: "Opciones del documento",
    choose_signature: "Firma avanzada:",
    edit_signature: "Editar firma",
    signature_hint: "Arrastra para mover, pellizca para redimensionar",
    watermark: "Marca de agua:",
    pdf_password: "Proteger PDF (contraseña):",
    premium_only: "(Premium)",
    document_type: "Tipo de documento detectado:",
    cachet: "Añadir sello automático:",
    center: "Centrado",
    diagonal: "Diagonal",
    bottom: "Abajo",
    open: "Abrir",
    premium: "Activar Premium",
    premium_hint: "Desbloquea todas las opciones pro y elimina los anuncios",
    dark_mode: "Modo oscuro",
    light_mode: "Modo claro",
    confirm: "Confirmar",
    history_empty: "No hay documentos guardados.",
    doc_facture: "Factura",
    doc_pieceid: "Documento de identidad",
    doc_note: "Nota manuscrita",
    doc_autre: "Otro documento",
    delete: "Eliminar",
    rename: "Renombrar",
    important: "Marcar como importante"
  },
  pt: {
    scan_document: "Digitalizar documento",
    import_gallery: "Importar da galeria",
    history: "Histórico",
    add_signature: "Adicionar assinatura",
    add_watermark: "Adicionar marca d'água",
    mask_tool: "Ocultar / desfocar",
    options: "Opções do documento",
    export_pdf: "Exportar como PDF",
    close: "Fechar",
    document_options: "Opções do documento",
    choose_signature: "Assinatura avançada:",
    edit_signature: "Editar assinatura",
    signature_hint: "Arraste para mover, faça pinça para redimensionar",
    signature_hint: "Arraste para mover, faça pinça para redimensionar",
    watermark: "Marca d'água:",
    pdf_password: "Proteger PDF (senha):",
    premium_only: "(Premium)",
    document_type: "Tipo de documento detectado:",
    cachet: "Adicionar selo automático:",
    center: "Centralizado",
    diagonal: "Diagonal",
    bottom: "Inferior",
    open: "Abrir",
    premium: "Ativar Premium",
    premium_hint: "Desbloqueie todas as opções pro e remova anúncios",
    dark_mode: "Modo escuro",
    light_mode: "Modo claro",
    confirm: "Confirmar",
    history_empty: "Nenhum documento salvo.",
    doc_facture: "Fatura",
    doc_pieceid: "Documento de identidade",
    doc_note: "Nota manuscrita",
    doc_autre: "Outro documento",
    delete: "Excluir",
    rename: "Renomear",
    important: "Marcar como importante"
  },
  ptbr: {
    scan_document: "Digitalizar documento",
    import_gallery: "Importar da galeria",
    history: "Histórico",
    add_signature: "Adicionar assinatura",
    add_watermark: "Adicionar marca d'água",
    mask_tool: "Ocultar / desfocar",
    options: "Opções do documento",
    export_pdf: "Exportar como PDF",
    close: "Fechar",
    document_options: "Opções do documento",
    choose_signature: "Assinatura avançada:",
    edit_signature: "Editar assinatura",
    watermark: "Marca d'água:",
    pdf_password: "Proteger PDF (senha):",
    premium_only: "(Premium)",
    document_type: "Tipo de documento detectado:",
    cachet: "Adicionar selo automático:",
    center: "Centralizado",
    diagonal: "Diagonal",
    bottom: "Inferior",
    open: "Abrir",
    premium: "Ativar Premium",
    premium_hint: "Desbloqueie todas as opções pro e remova anúncios",
    dark_mode: "Modo escuro",
    light_mode: "Modo claro",
    confirm: "Confirmar",
    history_empty: "Nenhum documento salvo.",
    doc_facture: "Fatura",
    doc_pieceid: "Documento de identidade",
    doc_note: "Nota manuscrita",
    doc_autre: "Outro documento",
    delete: "Excluir",
    rename: "Renomear",
    important: "Marcar como importante"
  }
};
